### ISSUE TITLE
lock.db2

### ISSUE THREAD

**Issue by weltmeyer** [Warpten/DBFilesClient.NET#1]
Hi, i get an error reading the most recent lock.db2 file.

It tries to read behind filesize:
Message: System.IO.EndOfStreamException: 'Unable to read beyond the end of the stream.' in LoadRecord
Code:
```c#
 storage = new Storage<LockDbcRecord>(@"data\DBFilesClient\Lock.db2", true);
```

BTW: Very handy tool you developed here :) tyvm!

**Comment by Warpten** [comment]
I'm seeing this issue just now; is it still happening?
