### ISSUE TITLE
Add support for WDC1 new format

### ISSUE THREAD

**Issue by alishahb** [Warpten/DBFilesClient.NET#3]
Format info can be found in WDBXEditor:
https://github.com/WowDevTools/WDBXEditor/blob/c4ba8687d702421b804555b8e32bdbbb5fd37be6/WDBXEditor/Reader/FileTypes/WDC1.cs

**Comment by Izidor** [comment]
Is this planned anytime soon? Would be nice to get a 7.3.5 spellwork :)

**Comment by Warpten** [comment]
(tm)

**Comment by Warpten** [comment]
I'm not gonna release it until I have decent performance. As of right now it is garbage on the least bit complex files. There's a branch 2.0.0.

**Comment by funjoker** [comment]
Is v2.0.0 supprting WDC1 or not? because implementation has WDC1

**Comment by Warpten** [comment]
No

**Comment by funjoker** [comment]
hm ok. Do you think it's ok to use in WPP or better waiting for v3 ?

**Comment by Warpten** [comment]
:bangbang: Support for DBFilesClient.NET has been discontinued. For an up-to-date libary, see [DBClientFiles.NET](http://github.com/Warpten/DBClientFiles.NET).
